/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_rpc_Rpc */

#ifndef _Included_org_fisco_bcos_sdk_rpc_Rpc
#define _Included_org_fisco_bcos_sdk_rpc_Rpc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    build
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/common/ConfigOption;)Lorg/fisco/bcos/sdk/rpc/Rpc;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_build
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_start
  (JNIEnv *, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    call
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_call
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    sendTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_sendTransaction
  (JNIEnv *, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getTransaction
  (JNIEnv *, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getTransactionReceipt
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getTransactionReceipt
  (JNIEnv *, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getBlockByHash
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZLorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getBlockByHash
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getBlockByNumber
 * Signature: (Ljava/lang/String;JZZLorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getBlockByNumber
  (JNIEnv *, jobject, jstring, jlong, jboolean, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getBlockHashByNumber
 * Signature: (Ljava/lang/String;JLorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getBlockHashByNumber
  (JNIEnv *, jobject, jstring, jlong, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getBlockNumber
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getBlockNumber
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getCode
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getSealerList
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getSealerList
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getObserverList
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getObserverList
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getPbftView
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getPbftView
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getPendingTxSize
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getPendingTxSize
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getSyncStatus
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getSyncStatus
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getSystemConfigByKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getSystemConfigByKey
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getTotalTransactionCount
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getTotalTransactionCount
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getPeers
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getPeers
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_rpc_Rpc
 * Method:    getNodeInfo
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_rpc_Rpc_getNodeInfo
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
