/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_sample_HelloWorldJNI */

#ifndef _Included_org_fisco_bcos_sdk_jni_sample_HelloWorldJNI
#define _Included_org_fisco_bcos_sdk_jni_sample_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_sample_HelloWorldJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_sample_HelloWorldJNI_sayHello
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
