/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_BcosSDK */

#ifndef _Included_org_fisco_bcos_sdk_BcosSDK
#define _Included_org_fisco_bcos_sdk_BcosSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_BcosSDK
 * Method:    build
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/BcosSDK;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_BcosSDK_build__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_BcosSDK
 * Method:    build
 * Signature: (Lorg/fisco/bcos/sdk/config/ConfigOption;)Lorg/fisco/bcos/sdk/BcosSDK;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_BcosSDK_build__Lorg_fisco_bcos_sdk_config_ConfigOption_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_BcosSDK
 * Method:    getRpc
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/rpc/Rpc;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_BcosSDK_getRpc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_fisco_bcos_sdk_BcosSDK
 * Method:    getAmop
 * Signature: ()Lorg/fisco/bcos/sdk/amop/Amop;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_BcosSDK_getAmop
  (JNIEnv *, jobject);

/*
 * Class:     org_fisco_bcos_sdk_BcosSDK
 * Method:    getEventSubscribe
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/subscribe/EventSubscribe;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_BcosSDK_getEventSubscribe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_fisco_bcos_sdk_BcosSDK
 * Method:    stopAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_BcosSDK_stopAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
