/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_subscribe_EventSubscribe */

#ifndef _Included_org_fisco_bcos_sdk_subscribe_EventSubscribe
#define _Included_org_fisco_bcos_sdk_subscribe_EventSubscribe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_subscribe_EventSubscribe
 * Method:    build
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/subscribe/EventSubscribe;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_subscribe_EventSubscribe_build
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_fisco_bcos_sdk_subscribe_EventSubscribe
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_subscribe_EventSubscribe_start
  (JNIEnv *, jobject);

/*
 * Class:     org_fisco_bcos_sdk_subscribe_EventSubscribe
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_subscribe_EventSubscribe_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_fisco_bcos_sdk_subscribe_EventSubscribe
 * Method:    subscribeEvent
 * Signature: (Lorg/fisco/bcos/sdk/subscribe/EventLogParams;Lorg/fisco/bcos/sdk/subscribe/EventCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_subscribe_EventSubscribe_subscribeEvent
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_subscribe_EventSubscribe
 * Method:    unsubscribeEvent
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/subscribe/EventCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_subscribe_EventSubscribe_unsubscribeEvent
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
