/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_BcosSDK */

#ifndef _Included_org_fisco_bcos_sdk_jni_BcosSDK
#define _Included_org_fisco_bcos_sdk_jni_BcosSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    newNativeObj
 * Signature: (Lorg/fisco/bcos/sdk/jni/common/JniConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_newNativeObj(JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    getRpcNativeObj
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_getRpcNativeObj(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    getAmopNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_getAmopNative(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    getEventSubNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_getEventSubNative(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_destroy(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
