/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_rpc_Rpc */

#ifndef _Included_org_fisco_bcos_sdk_jni_rpc_Rpc
#define _Included_org_fisco_bcos_sdk_jni_rpc_Rpc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    newNativeObj
 * Signature: (Lorg/fisco/bcos/sdk/jni/common/JniConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_newNativeObj(JNIEnv*, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_start(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_stop(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    genericMethod
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_rpc_Rpc_genericMethod__Ljava_lang_String_2Lorg_fisco_bcos_sdk_jni_rpc_RpcCallback_2(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    genericMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_rpc_Rpc_genericMethod__Ljava_lang_String_2Ljava_lang_String_2Lorg_fisco_bcos_sdk_jni_rpc_RpcCallback_2(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    genericMethod
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_rpc_Rpc_genericMethod__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Lorg_fisco_bcos_sdk_jni_rpc_RpcCallback_2(
    JNIEnv*, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    call
 * Signature:
 * (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_call(
    JNIEnv*, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    sendTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_sendTransaction(
    JNIEnv*, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getTransaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getTransaction(
    JNIEnv*, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getTransactionReceipt
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getTransactionReceipt(
    JNIEnv*, jobject, jstring, jstring, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getBlockByHash
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getBlockByHash(
    JNIEnv*, jobject, jstring, jstring, jboolean, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getBlockByNumber
 * Signature: (Ljava/lang/String;JZZLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getBlockByNumber(
    JNIEnv*, jobject, jstring, jlong, jboolean, jboolean, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getBlockHashByNumber
 * Signature: (Ljava/lang/String;JLorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getBlockHashByNumber(
    JNIEnv*, jobject, jstring, jlong, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getBlockNumber
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getBlockNumber(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getCode(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getSealerList
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getSealerList(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getObserverList
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getObserverList(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getPbftView
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getPbftView(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getPendingTxSize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getPendingTxSize(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getSyncStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getSyncStatus(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getSystemConfigByKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getSystemConfigByKey(
    JNIEnv*, jobject, jstring, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getTotalTransactionCount
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getTotalTransactionCount(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getPeers
 * Signature: (Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getPeers(JNIEnv*, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getGroupList
 * Signature: (Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getGroupList(JNIEnv*, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getGroupInfo
 * Signature: (Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getGroupInfo(
    JNIEnv*, jobject, jstring, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getGroupInfoList
 * Signature: (Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getGroupInfoList(
    JNIEnv*, jobject, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_rpc_Rpc
 * Method:    getGroupNodeInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/fisco/bcos/sdk/jni/rpc/RpcCallback;)V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_rpc_Rpc_getGroupNodeInfo(
    JNIEnv*, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
