/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_sample_WsToolJNI */

#ifndef _Included_org_fisco_bcos_sdk_jni_sample_WsToolJNI
#define _Included_org_fisco_bcos_sdk_jni_sample_WsToolJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_sample_WsToolJNI
 * Method:    newWsToolJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_sample_WsToolJNI_newWsToolJNI(JNIEnv*, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_sample_WsToolJNI
 * Method:    validIP
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_fisco_bcos_sdk_jni_sample_WsToolJNI_validIP(
    JNIEnv*, jobject, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_sample_WsToolJNI
 * Method:    validPort
 * Signature: (S)Z
 */
JNIEXPORT jboolean JNICALL Java_org_fisco_bcos_sdk_jni_sample_WsToolJNI_validPort(
    JNIEnv*, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
