/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_BcosSDK */

#ifndef _Included_org_fisco_bcos_sdk_jni_BcosSDK
#define _Included_org_fisco_bcos_sdk_jni_BcosSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    newNativeObj
 * Signature: (Lorg/fisco/bcos/sdk/jni/common/JniConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_newNativeObj
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
