/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_BcosSDK */

#ifndef _Included_org_fisco_bcos_sdk_jni_BcosSDK
#define _Included_org_fisco_bcos_sdk_jni_BcosSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    newNativeObj
 * Signature: (Lorg/fisco/bcos/sdk/jni/common/JniConfig;)J
 */
JNIEXPORT jlong JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_newNativeObj
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    build
 * Signature: (Lorg/fisco/bcos/sdk/jni/common/JniConfig;)Lorg/fisco/bcos/sdk/jni/BcosSDK;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_build
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    getRpc
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/rpc/Rpc;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_getRpc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    getAmop
 * Signature: ()Lorg/fisco/bcos/sdk/jni/amop/Amop;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_getAmop
  (JNIEnv *, jobject);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    getEventSubscribe
 * Signature: (Ljava/lang/String;)Lorg/fisco/bcos/sdk/jni/event/EventSubscribe;
 */
JNIEXPORT jobject JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_getEventSubscribe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_BcosSDK
 * Method:    stopAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fisco_bcos_sdk_jni_BcosSDK_stopAll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
