/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj */

#ifndef _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj
#define _Included_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj
 * Method:    createDeployContractSignedTransaction
 * Signature:
 * (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj_createDeployContractSignedTransaction(
    JNIEnv*, jclass, jlong, jstring, jstring, jstring, jstring, jlong, jstring, jstring);

/*
 * Class:     org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj
 * Method:    createSignedTransaction
 * Signature:
 * (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_org_fisco_bcos_sdk_jni_utilities_tx_TransactionBuilderJniObj_createSignedTransaction(
    JNIEnv*, jclass, jlong, jstring, jstring, jstring, jstring, jlong, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
